const links = [
	{label:"Week 1",
		url:"./week01/index.html"},
	{label:"Week 2",
		url:"./week02/index.html"},
	{label:"Week 3",
		url:"./week03/index.html"},
	{label:"Week 4",
		url:"./week04/index.html"},
	{label:"Week 5",
		url:"./week05/index.html"},
	{label:"Week 6",
		url:"./week05/index.html"},
	{label:"Week 7",
		url:"./week07/index.html"},
	{label:"Week 8",
		url:"./week08/index.html"},
	{label:"Week 9",
		url:"./week09/index.html"},
	{label:"Week 10",
		url:"./week10/index.html"}
]